services:
  - type: web
    name: depenses-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    staticPublishPath: static